version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root   # Only use MYSQL_ROOT_PASSWORD for the root user
      MYSQL_DATABASE: productdataservice  # Database name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/productdataservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  # Use root password here
    ports:
      - "8082:8081"  # Change 8081 to 8082, or use another available port
volumes:
  mysql_data:
    driver: local

